services:
  redis:
    image: redis:7-alpine
    container_name: redis_agents
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  db:
    image: supabase/postgres:17.4.1.036
    container_name: reddia-db
    restart: always
    environment:
      POSTGRES_USER: user_reddia
      POSTGRES_PASSWORD: password_reddia
      POSTGRES_DB: reddia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
